name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint || echo "Linting completed with warnings"

      - name: Build project
        run: bun run build

      - name: Verify build output
        run: |
          ls -la dist/
          test -f dist/index.js
          test -f dist/index.d.ts
          test -f dist/types.js
          test -f dist/types.d.ts

      - name: Check package can be imported
        run: |
          cd dist
          node -e "const sdk = require('./index.js'); console.log('✅ Package can be imported successfully');" 